### ISSUE TITLE
VSCode Arduino release 0.2.12 candidate

### ISSUE THREAD

**Issue by lirenhe** [Microsoft/vscode-arduino#498]
Bugs
- [x] #415 [P1] Board manager / Library manager do not work with portable Arduino installation
- [x] #457 [P1] the Arduino Extension should do incrementally change to the additional URLs but not remove the existing links
- [x] #483 [P2] Arduino Plugin Moves Terminal Connect Button
- [x] #450 [P2] Cannot set output folder to absolute path
- [x] #497 [P2] Unable to add '\r\n' when sending text to serial monitor
- [x] #428 [P2] Unable to start debugging for file path contain space
- [x] #414 [P2] Board manager mixes up packages from different sources
- [x] #394  Disable VSCode Board Manager automatic update
- [x] #471 [P2] Unable select board configuration when the folder in Onedrive
- [x] #455 Add support to multi-root workspaces

**Comment by itechnocrat** [comment]
Hello!
I apologize.

As a result, is there support for multi-root workspaces in the VS Code for Arduino extensions?
I couldn't understand it.

So far I only see that the Code does not work with multi-root workspaces with Arduino extensions.
I can record a screen demo of this, but maybe I'm doing something wrong.

Can you write how to work with multi-root workspaces in VS Code with Arduino extensions (Id: vsciot-vscode.vscode-arduino)?
