### ISSUE TITLE
VSCode Arduino release 0.2.15 candidate

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode-arduino#511]
- [x] #438 [Blocked: `includePath` is not recursive] The Extension should automagically fill the c_cpp_properties.json, so intellisense works out of the box
- [x] #481 Command Palette Should Allow (Re)Setting Sketch File
- [x] #137 After clicking "verify", the info "verifying" keeps showing w/o more hints
- [x] #411 Pre Build command
- [x] #407 Upload Using Programmer
- [x] #495 "Detected board" incorrect
- [x] #530 TestingOpen output on the serial monitor

**Comment by ArthurMa1978** [comment]
Target on Sprint 135
