### ISSUE TITLE
VSCode Arduino release 0.2.16 candidate

### ISSUE THREAD

**Issue by Sneezry** [Microsoft/vscode-arduino#567]
- [x] #533 Arduino: Examples command displays an empty tab 
- [x] #566 Check Arduino IDE before updating package index file 
- [x] #565 Adds way to skip header file provider
