### ISSUE TITLE
VSCode Arduino release 0.2.17 candidate

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-arduino#576]
- [x] #568 Tell user to close serial port monitor when uploading failed due to the serial port monitor is opening, or just close it before upload
- [x] #555 Please help fix errors that frequently happened
- [x] #583 Check Arduino IDE in command palette when cannot resolve arduino path
- [x]  #586 g++ not find after upgrading the board sdk to a new version
