### ISSUE TITLE
VSCode Arduino release 0.2.18 candidate

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-arduino#593]
- [x] #591 "Verifying" is misspelled in the status message in the status bar
- [x] #223 My WeMos D1 is not auto detected
- [x] #605 Config setting descriptions are unlcear
