### ISSUE TITLE
VSCode Arduino release 0.2.20 candidate 

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-arduino#617]
- [x] #616 Set default Baud Rate
- [x] #611 " [Error] Exit with code=undefined " -> too little information
- [x] #577 I verify and revived this error :Exit with code=undefined
