### ISSUE TITLE
VSCode Arduino release 0.2.23 candidate

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-arduino#689]
- [x] #686 Arduino extension shouldn't rename C++ language to "Arduino"
- [x] #701  Upgrade to VS Code's webview API 
- [x] #685 add debugging support for uno
- [x] #703 Add Wio LTE M1/NB1(BG96) board 
- [x] #681 Fixed major grammatical issues & formatting issues
- [x] #679 Spelling and grammar updates to README
- [x] #665 added contribution guidelines
- [x] #652 add sketch folder to examples
