### ISSUE TITLE
VSCode Arduino release 0.2.24 candidate

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-arduino#713]
- [x] #634 Add support for cmsis-dap with Keil Software vid
- [x] #693 Save the selected programmer in Arduino.json 
- [x] #687 Latest version of Arduino (1.8.7) does not work with extension
