### ISSUE TITLE
VSCode Arduino release 0.2.25 candidate

### ISSUE THREAD

**Issue by czgtest** [Microsoft/vscode-arduino#734]
- [x] #720  Wrong arduino.commandPath in Doc for MacOS 
- [x] #729  fix breaking change issue for node 10
- [x] #730  fix serialport build err under unix
- [x] #731  add binary dependency for electron 3.0.10
- [x] #582   Upload Using a Status Bar Button
